1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,7 +1,39 @@
 #!/usr/bin/env bash
-# Installs nginx server
-apt-get update
-apt-get -y install nginx
-ufw allow 'Nginx HTTP'
-echo "Hello World!" > /var/www/html/index.html
-service nginx start
+# Script that install nginx server and write content to the root.
+sudo apt update -y
+sudo apt install nginx -y
+sudo echo "Holberton School" > /var/www/html/index.html
+sudo service nginx restart
+
+
+# This is another way of doing this challenge by writing the content directly to the the default index.html
+# sudo apt-get -y update && \
+# sudo apt-get -y install nginx
+# if [ $? -eq 0 ];
+# then
+#     sudo chown -R $USER:$USER /etc/nginx/nginx.conf
+#     sudo echo -e \
+#     "http {
+#         server {
+#             listen 80;
+#             location / {
+#                 root /var/www/astro.site
+#             }
+#         }
+#     }" > /etc/nginx/nginx.conf
+#    sudo mkdir -p /var/www/astro.site
+#    sudo chown -R $USER:$USER /var/www/astro.site
+#    sudo echo "Holberton School" > /var/www/astro.site/index.html
+
+#     sudo service nginx start
+#     if [ $? -ne 0 ]
+#     then
+#         echo  "Can't start nginx"
+#         exit 1
+#     fi
+# else
+#     echo "Can't install nginx"
+#     exit 1
+# fi
+# echo "Holberton School"
+
